### PR TITLE
Add coveralls support to travis config file and add badge to README

### PR DESCRIPTION
**Pull request by mschmidt87**
This PR adds coveralls support to the repo.

### CODE REVIEW

**Comment by mschmidt87** [comment]
The test fails because we now install the h5py_wrapper via pip and the release version does not support python3.

However, why does it sucessfully install the wrapper then via pip? Shouldn't that fail because the version is not py3-compatible?

As a workaround, we can build in an if-clause to skip the installation of the wrapper when testing with python 3 but I don't understand why `pip install h5py_wrapper` works with python 3? Did we do something wrong when publishing the wrapper?

**Comment by jakobj** [comment]
Could be that we forgot to enter some details. When you check numpy on pypi (https://pypi.python.org/pypi/numpy/1.13.0rc1) you see that they list the Python versions that this packages is compatible with explicitly:
```
Requires Python: >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.* 
```

Maybe we need to add something similar? Alternatively we could just create a new release with Python3 support?

**Comment by mschmidt87** [comment]
Yes, I think we forgot to add that to `setup.py` in the `h5py_wrapper`.
Okay, we should add that information in the next release of the wrapper. I would like to wait with the Python3-release to fix the remaining issues with milestone 1.0.3 before that. They should be straightforward to solve. 

For now, I can add here an if-clause to prevent travis from installing the wrapper when testing python 3. Okay?

**Comment by jakobj** [comment]
I'm merging independent of h5py_wrapper's Python3 support, since this PR does not really change anything about that. We will need to fix travis in a separate PR :+1:

**Pull request merged**
